# Site settings
title: smarisa.github.io
email: samuel.marisa@gmail.com
description: >
  This is my awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://smarisa.github.io" # the base hostname & protocol for your site
twitter_username: shmarisa
github_username:  smarisa

# Build settings
markdown: kramdown
