# Site settings
title: Samuel Sydänlammi
email: fn.ln@gmail.com
description: >
  This is my minimalist personal website created in 2019 and generously hosted by GitHub.
baseurl: ""
url: "http://sjjsy.github.io" # the base hostname & protocol for your site
github_username:  sjjsy

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
